apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"    
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: trodrigo/api-produto:v1
          ports:
          - containerPort: 8085
          env:
            - name: MONGODB_URI
              value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin